### ISSUE TITLE
entry point must be defined

### ISSUE THREAD

**Issue by Artikus8** [CodeRedRL/CodeRed-Universal#2]
I guess the problem is with me but I searched for the solution, I couldn't find it, what I tried did not work I wanted to ask 
In this way, those who have this problem can easily solve it. '' 
![Adsız](https://user-images.githubusercontent.com/46781129/119583997-73e27400-bdd0-11eb-8ed8-ad11bfc44827.png)

**Comment by Artikus8** [comment]
I guess I solved the problem by adding the following into main codes
`
int main()
{
	//you can leave it empty
	return 0;
}
`
I have a new problem now 
![Screenshot_1](https://user-images.githubusercontent.com/46781129/119585612-af327200-bdd3-11eb-8a31-815f61367d74.png)

Compiling is okay but I guess it shouldn't be like this xd 

`1>------ Build started: Project: CodeRedUniversal, Configuration: Debug x64 ------
1>Core.cpp
1>c:\users\zipth\desktop\codered-universal-main\placeholdersdk\gamedefines.hpp(452): warning C4267: '=': conversion from 'size_t' to 'int32_t', possible loss of data
1>c:\users\zipth\desktop\codered-universal-main\placeholdersdk\gamedefines.hpp(484): warning C4267: '=': conversion from 'size_t' to 'int32_t', possible loss of data
1>c:\users\zipth\desktop\codered-universal-main\components\components\core.cpp(62): warning C4477: 'sprintf_s' : format string '%llx' requires an argument of type 'unsigned __int64', but variadic argument 1 has type 'TArray<UObject *> *'
1>c:\users\zipth\desktop\codered-universal-main\components\components\core.cpp(65): warning C4477: 'sprintf_s' : format string '%llx' requires an argument of type 'unsigned __int64', but variadic argument 1 has type 'TArray<FNameEntry *> *'
1>c:\users\zipth\desktop\codered-universal-main\placeholdersdk\gamedefines.hpp(161): warning C4715: 'TArray<UObject *>::At': not all control paths return a value
1>c:\users\zipth\desktop\codered-universal-main\placeholdersdk\gamedefines.hpp(377): warning C4715: 'FName::GetEntry': not all control paths return a value
1>c:\users\zipth\desktop\codered-universal-main\placeholdersdk\gamedefines.hpp(161): warning C4715: 'TArray<FNameEntry *>::At': not all control paths return a value
1>CodeRedUniversal.vcxproj -> C:\Users\zipth\Desktop\CodeRed-Universal-main\x64\Debug\CodeRedUniversal.exe
1>Done building project "CodeRedUniversal.vcxproj".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
`

**Comment by ItsBranK** [comment]
You're compliling as an exe when you should be compiling as a dll, the entrypoint is in dllmain.cpp. Internal sdk modding like this can only be done via an injected dll.

**Comment by Artikus8** [comment]
oh thank you for the information.
Unnecessary question sorry ..
